name: "ArXiv HTML Content issue"
description: Testing for Template Now!
body:
  - type: markdown
    attributes:
      value: |
        ### Before you start

        **This is just a testing issue report**
        ↩ Developing.

        **Write base on**
        ↩ https://github.com/mdn/content/blob/main/.github/ISSUE_TEMPLATE/content-bug.yml?plain=1

        **Feasible link format**
        🙋 [Report issue](https://github.com/mdn/content/issues/new?template=page-report.yml&amp;mdn-url=testestest&section=test2)
        ↩ https://github.com/mdn/content/issues/new?template=page-report.yml&amp;mdn-url=testestest&section=test2
  - type: markdown
    id: mkid
    attribute:
      value: 
    
  - type: input
    id: articleTitle
    attributes:
      label: Article Title
      description: The link to the page this issue is about or, if it's about multiple pages, an example or most important page.
    validations:
      required: true
  # -- BEGIN fields that correspond to `page-report.yml` —-
  # If you edit these fields, edit them in both files!
  - type: input
    id: section
    attributes:
      label: What specific section or headline is this issue about?
  - type: textarea
    id: problem
    attributes:
      label: What information was incorrect, unhelpful, or incomplete?
    validations:
      required: true
  - type: textarea
    id: expected
    attributes:
      label: What did you expect to see?
    validations:
      required: true
  - type: textarea
    id: references
    attributes:
      label: Do you have any supporting links, references, or citations?
      description: Link to information that helps us confirm your issue.
  - type: textarea
    id: more-info
    attributes:
      label: Do you have anything more you want to share?
      description: For example, steps to reproduce a bug, screenshots, screen recordings, or sample code
  # -- END fields that correspond to `page-report.yml` —-
