name: "ArXiv HTML Content issue"
description: Testing Template!
body:
  - type: markdown
    attributes:
      value: |
        ### Before you start

        **This is a testing report template**
        ↩ Developing.

        **Report general problem**
        🙋 [Report issue](https://github.com/YiChen8185/TestForGitHubIssue/issues/new?assignees=&labels=&projects=&title=General_Problem&template=bug_report.yml&articleTitle=GeneralProblem)
        
        **Problem**
        ‼️ Chrome may disable the ability to open new windows, and users will need to manually allow it. This does not happen in old one.

        
        ---

  - type: textarea
    id: extra-info
    attributes:
      label: Please free feel to share anything more?
      description: For example, steps to reproduce a bug, screenshots, screen recordings, or sample code.
      
  - type: dropdown
    id: device
    attributes:
      label: What device are you using?
      options:
        - Mobile
        - Desktop
        - IPad
        - VR?
    validations:
      required: true
  
  
  - type: checkboxes
    id: comfirm
    attributes:
      label: Is everydata looks good
      description: Check the box.
      options:
        - label: Comfirm (required.)
          required: true
        - label: Hello World
        - label: ArXiv
        - label: Ar5iv


  # Below is autofill section.
  - type: markdown
    attributes:
      value: |
        ---
        <br>
        <br>
        <br>
        <br>
        <br>
        <br>
        
        # Set automatically. Do not modify.
        
        
  - type: textarea
    id: description
    attributes:
      description: Set automatically. Do not modify.
      label: Description
    validations:
      required: true
  
  - type: textarea
    id: uniqueId
    attributes:
      label: UniqueId for the Article
      description: Set automatically. Do not modify.
    validations:
      required: true
